"""Schrijft alle component-templates naar prompts/components/."""
from pathlib import Path

base = Path("/workspace/prompts/components")

templates = {
"hero/split.tsx": '<section className="py-16 md:py-24 bg-background">\n  <div className="container mx-auto px-4">\n    <div className="flex flex-col md:flex-row items-center gap-12">\n      <div className="flex-1">\n        <h1 className="font-heading text-4xl md:text-5xl font-bold leading-tight mb-5">[[ headline ]]</h1>\n        [[ ?subline ]]<p className="text-muted-foreground text-lg leading-relaxed mb-8">[[ subline ]]</p>[[ / ]]\n        <div className="flex flex-col sm:flex-row gap-3">\n          <Link href="[[ cta_primary_link ]]" className="inline-flex items-center gap-2 bg-primary hover:bg-primary/90 text-primary-foreground font-semibold px-6 py-3 rounded-sm transition-colors">[[ cta_primary_text ]] <ArrowRight className="w-4 h-4" /></Link>\n          [[ ?cta_secondary_text ]]<Link href="[[ cta_secondary_link ]]" className="inline-flex items-center gap-2 border border-border hover:border-primary text-foreground font-semibold px-6 py-3 rounded-sm transition-colors">[[ cta_secondary_text ]]</Link>[[ / ]]\n        </div>\n      </div>\n      [[ ?image ]]<div className="flex-1"><img src="/[[ image ]]" alt="[[ headline ]]" className="w-full h-80 md:h-96 object-cover rounded-xl shadow-lg" /></div>[[ / ]]\n    </div>\n  </div>\n</section>',

"hero/gradient.tsx": '<section className="py-24 md:py-32 bg-gradient-to-br from-primary/10 via-background to-background">\n  <div className="container mx-auto px-4 text-center">\n    <h1 className="font-heading text-4xl md:text-6xl font-bold leading-tight mb-5 max-w-3xl mx-auto">[[ headline ]]</h1>\n    [[ ?subline ]]<p className="text-muted-foreground text-lg md:text-xl leading-relaxed mb-8 max-w-2xl mx-auto">[[ subline ]]</p>[[ / ]]\n    <div className="flex flex-col sm:flex-row gap-3 justify-center">\n      <Link href="[[ cta_primary_link ]]" className="inline-flex items-center gap-2 bg-primary hover:bg-primary/90 text-primary-foreground font-semibold px-7 py-3.5 rounded-sm transition-colors">[[ cta_primary_text ]] <ArrowRight className="w-4 h-4" /></Link>\n      [[ ?cta_secondary_text ]]<Link href="[[ cta_secondary_link ]]" className="inline-flex items-center gap-2 border border-primary text-primary hover:bg-primary/10 font-semibold px-7 py-3.5 rounded-sm transition-colors">[[ cta_secondary_text ]]</Link>[[ / ]]\n    </div>\n  </div>\n</section>',

"page_hero/default.tsx": '<section className="py-14 md:py-20 bg-primary text-primary-foreground">\n  <div className="container mx-auto px-4">\n    <h1 className="font-heading text-3xl md:text-4xl font-bold mb-2">[[ title ]]</h1>\n    [[ ?subtitle ]]<p className="text-primary-foreground/75 text-lg">[[ subtitle ]]</p>[[ / ]]\n  </div>\n</section>',

"services/cards-3.tsx": '<section className="py-16 md:py-20 bg-background">\n  <div className="container mx-auto px-4">\n    [[ ?headline ]]<div className="text-center mb-12"><h2 className="font-heading text-3xl md:text-4xl font-bold mb-3">[[ headline ]]</h2>[[ ?intro ]]<p className="text-muted-foreground text-lg max-w-2xl mx-auto">[[ intro ]]</p>[[ / ]]</div>[[ / ]]\n    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">\n      [[ *items ]]<div className="bg-card border border-border rounded-xl p-6 hover:shadow-md transition-shadow">\n        [[ ?.icon ]]<[[ ~.icon ]] className="w-8 h-8 text-primary mb-4" />[[ / ]]\n        <h3 className="font-heading font-semibold text-lg mb-2">[[ .title ]]</h3>\n        <p className="text-muted-foreground text-sm leading-relaxed">[[ .description ]]</p>\n        [[ ?.price ]]<p className="text-sm font-semibold text-primary mt-2">[[ .price ]]</p>[[ / ]]\n      </div>[[ / ]]\n    </div>\n  </div>\n</section>',

"services/cards-4.tsx": '<section className="py-16 md:py-20 bg-background">\n  <div className="container mx-auto px-4">\n    [[ ?headline ]]<div className="text-center mb-12"><h2 className="font-heading text-3xl md:text-4xl font-bold mb-3">[[ headline ]]</h2>[[ ?intro ]]<p className="text-muted-foreground text-lg max-w-2xl mx-auto">[[ intro ]]</p>[[ / ]]</div>[[ / ]]\n    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">\n      [[ *items ]]<div className="bg-card border border-border rounded-xl p-5 hover:shadow-md transition-shadow">\n        [[ ?.icon ]]<[[ ~.icon ]] className="w-7 h-7 text-primary mb-3" />[[ / ]]\n        <h3 className="font-heading font-semibold mb-1">[[ .title ]]</h3>\n        <p className="text-muted-foreground text-sm">[[ .description ]]</p>\n        [[ ?.price ]]<p className="text-sm font-semibold text-primary mt-2">[[ .price ]]</p>[[ / ]]\n      </div>[[ / ]]\n    </div>\n  </div>\n</section>',

"about/split-image-right.tsx": '<section className="py-16 md:py-20 bg-muted/30">\n  <div className="container mx-auto px-4">\n    <div className="flex flex-col md:flex-row items-center gap-10 md:gap-16">\n      <div className="flex-1">\n        <h2 className="font-heading text-3xl md:text-4xl font-bold mb-4">[[ headline ]]</h2>\n        <p className="text-muted-foreground leading-relaxed">[[ body ]]</p>\n        [[ ?bullets ]]<ul className="space-y-2 mt-4">[[ *bullets ]]<li className="flex items-start gap-2 text-sm text-muted-foreground"><Check className="w-5 h-5 text-primary mt-0.5 shrink-0" /><span>[[ .value ]]</span></li>[[ / ]]</ul>[[ / ]]\n        [[ ?cta_text ]]<Link href="[[ cta_link ]]" className="inline-flex items-center gap-2 text-primary font-semibold hover:underline mt-5"><span>[[ cta_text ]]</span><ArrowRight className="w-4 h-4" /></Link>[[ / ]]\n      </div>\n      [[ ?image ]]<div className="w-full md:w-1/2"><img src="/[[ image ]]" alt="[[ headline ]]" className="w-full h-72 md:h-full object-cover rounded-xl" /></div>[[ / ]]\n    </div>\n  </div>\n</section>',

"about/split-image-left.tsx": '<section className="py-16 md:py-20 bg-muted/30">\n  <div className="container mx-auto px-4">\n    <div className="flex flex-col md:flex-row items-center gap-10 md:gap-16">\n      [[ ?image ]]<div className="w-full md:w-1/2"><img src="/[[ image ]]" alt="[[ headline ]]" className="w-full h-72 md:h-full object-cover rounded-xl" /></div>[[ / ]]\n      <div className="flex-1">\n        <h2 className="font-heading text-3xl md:text-4xl font-bold mb-4">[[ headline ]]</h2>\n        <p className="text-muted-foreground leading-relaxed">[[ body ]]</p>\n        [[ ?bullets ]]<ul className="space-y-2 mt-4">[[ *bullets ]]<li className="flex items-start gap-2 text-sm text-muted-foreground"><Check className="w-5 h-5 text-primary mt-0.5 shrink-0" /><span>[[ .value ]]</span></li>[[ / ]]</ul>[[ / ]]\n        [[ ?cta_text ]]<Link href="[[ cta_link ]]" className="inline-flex items-center gap-2 text-primary font-semibold hover:underline mt-5"><span>[[ cta_text ]]</span><ArrowRight className="w-4 h-4" /></Link>[[ / ]]\n      </div>\n    </div>\n  </div>\n</section>',

"stats/bar.tsx": '<section className="py-14 bg-primary text-primary-foreground">\n  <div className="container mx-auto px-4">\n    [[ ?headline ]]<h2 className="font-heading text-2xl font-bold text-center mb-8">[[ headline ]]</h2>[[ / ]]\n    <div className="grid grid-cols-2 md:grid-cols-4 gap-8">\n      [[ *items ]]<div className="text-center"><div className="font-heading text-4xl md:text-5xl font-bold">[[ .value ]]</div><div className="text-primary-foreground/75 text-sm mt-1">[[ .label ]]</div></div>[[ / ]]\n    </div>\n  </div>\n</section>',

"cta/centered.tsx": '<section className="py-16 md:py-20 bg-primary text-primary-foreground">\n  <div className="container mx-auto px-4 text-center">\n    <h2 className="font-heading text-3xl md:text-4xl font-bold mb-3">[[ headline ]]</h2>\n    [[ ?body ]]<p className="text-primary-foreground/80 text-lg mb-8 max-w-xl mx-auto">[[ body ]]</p>[[ / ]]\n    <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">\n      <Link href="[[ cta_link ]]" className="inline-flex items-center gap-2 bg-white text-primary hover:bg-white/90 font-semibold px-7 py-3.5 rounded-sm transition-colors">[[ cta_text ]] <ArrowRight className="w-4 h-4" /></Link>\n      [[ ?phone ]]<a href="tel:[[ phone ]]" className="inline-flex items-center gap-2 text-primary-foreground/80 hover:text-primary-foreground"><Phone className="w-4 h-4" />[[ phone ]]</a>[[ / ]]\n      [[ ?whatsapp ]]<a href="https://wa.me/[[ whatsapp ]]" target="_blank" rel="noopener" className="inline-flex items-center gap-2 text-primary-foreground/80 hover:text-primary-foreground"><MessageCircle className="w-4 h-4" />WhatsApp</a>[[ / ]]\n    </div>\n  </div>\n</section>',

"faq/default.tsx": '<section className="py-16 md:py-20 bg-background">\n  <div className="container mx-auto px-4 max-w-3xl">\n    <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-10">[[ headline ]]</h2>\n    <Accordion type="single" collapsible className="space-y-2">\n      [[ *items ]]<AccordionItem value="q[[ .index ]]">\n        <AccordionTrigger className="font-heading font-semibold text-left">[[ .question ]]</AccordionTrigger>\n        <AccordionContent className="text-muted-foreground leading-relaxed">[[ .answer ]]</AccordionContent>\n      </AccordionItem>[[ / ]]\n    </Accordion>\n  </div>\n</section>',

"contact/with-form.tsx": '<section className="py-16 md:py-20 bg-muted/30">\n  <div className="container mx-auto px-4">\n    <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-12">[[ headline ]]</h2>\n    <div className="flex flex-col md:flex-row gap-12 max-w-4xl mx-auto">\n      <div className="flex-1 space-y-6">\n        [[ ?phone ]]<div className="flex items-start gap-3"><Phone className="w-5 h-5 text-primary mt-0.5 shrink-0" /><div><div className="font-medium">Telefoon</div><a href="tel:[[ phone ]]" className="text-muted-foreground hover:text-primary">[[ phone ]]</a></div></div>[[ / ]]\n        [[ ?email ]]<div className="flex items-start gap-3"><Mail className="w-5 h-5 text-primary mt-0.5 shrink-0" /><div><div className="font-medium">E-mail</div><a href="mailto:[[ email ]]" className="text-muted-foreground hover:text-primary">[[ email ]]</a></div></div>[[ / ]]\n        [[ ?address ]]<div className="flex items-start gap-3"><MapPin className="w-5 h-5 text-primary mt-0.5 shrink-0" /><div><div className="font-medium">Adres</div><p className="text-muted-foreground">[[ address ]]</p></div></div>[[ / ]]\n      </div>\n      <div className="flex-1"><form action="https://formspree.io/f/FORMSPREE_ID" method="POST" className="space-y-4"><input type="hidden" name="_subject" value="Nieuw bericht via website" /><input type="text" name="_gotcha" style={{ display: "none" }} /><div><label className="block text-sm font-medium mb-1.5">Naam</label><input type="text" name="name" required className="w-full border border-input bg-background rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary" /></div><div><label className="block text-sm font-medium mb-1.5">E-mail</label><input type="email" name="email" required className="w-full border border-input bg-background rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary" /></div><div><label className="block text-sm font-medium mb-1.5">Bericht</label><textarea name="message" rows={5} required className="w-full border border-input bg-background rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary resize-none" /></div><button type="submit" className="w-full bg-primary hover:bg-primary/90 text-primary-foreground font-semibold py-2.5 rounded-md transition-colors">Verstuur bericht</button></form></div>\n    </div>\n  </div>\n</section>',

"contact/info-only.tsx": '<section className="py-16 md:py-20 bg-muted/30">\n  <div className="container mx-auto px-4 max-w-xl">\n    <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-10">[[ headline ]]</h2>\n    <div className="space-y-6">\n      [[ ?phone ]]<div className="flex items-start gap-3"><Phone className="w-5 h-5 text-primary mt-0.5" /><div><div className="font-medium">Telefoon</div><a href="tel:[[ phone ]]" className="text-muted-foreground hover:text-primary">[[ phone ]]</a></div></div>[[ / ]]\n      [[ ?email ]]<div className="flex items-start gap-3"><Mail className="w-5 h-5 text-primary mt-0.5" /><div><div className="font-medium">E-mail</div><a href="mailto:[[ email ]]" className="text-muted-foreground hover:text-primary">[[ email ]]</a></div></div>[[ / ]]\n      [[ ?address ]]<div className="flex items-start gap-3"><MapPin className="w-5 h-5 text-primary mt-0.5" /><div><div className="font-medium">Adres</div><p className="text-muted-foreground">[[ address ]]</p></div></div>[[ / ]]\n    </div>\n  </div>\n</section>',

"team/cards-3.tsx": '<section className="py-16 md:py-20 bg-background">\n  <div className="container mx-auto px-4">\n    <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-12">[[ headline ]]</h2>\n    <div className="grid grid-cols-2 md:grid-cols-3 gap-8">\n      [[ *members ]]<div className="text-center">\n        [[ ?.photo ]]<img src="/[[ .photo ]]" alt="[[ .name ]]" className="w-32 h-32 rounded-full object-cover mx-auto mb-4" />[[ / ]]\n        <h3 className="font-heading font-semibold text-lg">[[ .name ]]</h3>\n        <p className="text-primary text-sm font-medium">[[ .role ]]</p>\n        [[ ?.bio ]]<p className="text-muted-foreground text-sm mt-1">[[ .bio ]]</p>[[ / ]]\n      </div>[[ / ]]\n    </div>\n  </div>\n</section>',

"gallery/grid-3.tsx": '<section className="py-16 md:py-20 bg-muted/30">\n  <div className="container mx-auto px-4">\n    [[ ?headline ]]<h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-10">[[ headline ]]</h2>[[ / ]]\n    <div className="grid grid-cols-2 md:grid-cols-3 gap-3">\n      [[ *images ]]<div className="overflow-hidden rounded-lg aspect-square"><img src="/[[ .src ]]" alt="[[ .alt ]]" className="w-full h-full object-cover hover:scale-105 transition-transform duration-300" /></div>[[ / ]]\n    </div>\n  </div>\n</section>',

"testimonials/cards.tsx": '<section className="py-16 md:py-20 bg-muted/30">\n  <div className="container mx-auto px-4">\n    <h2 className="font-heading text-3xl md:text-4xl font-bold text-center mb-10">[[ headline ]]</h2>\n    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">\n      [[ *items ]]<div className="bg-card border border-border rounded-xl p-6"><div className="flex gap-0.5 mb-3"><Star className="w-4 h-4 fill-primary text-primary" /><Star className="w-4 h-4 fill-primary text-primary" /><Star className="w-4 h-4 fill-primary text-primary" /><Star className="w-4 h-4 fill-primary text-primary" /><Star className="w-4 h-4 fill-primary text-primary" /></div><p className="text-muted-foreground leading-relaxed mb-4">"[[ .text ]]"</p><div className="font-semibold text-sm">[[ .name ]]</div>[[ ?.subtitle ]]<div className="text-xs text-muted-foreground">[[ .subtitle ]]</div>[[ / ]]</div>[[ / ]]\n    </div>\n  </div>\n</section>',
}

for path, content in templates.items():
    full = base / path
    full.parent.mkdir(parents=True, exist_ok=True)
    full.write_text(content, encoding="utf-8")

files = list(base.rglob("*.tsx"))
print(f"Templates: {len(files)}")
for f in sorted(files):
    print(f"  {f.relative_to(base)}")
